### ISSUE TITLE
Current head on Fedora 20 causes a null pointer exception when starting decerver

### ISSUE THREAD

**Issue by DennisHaper** [eris-ltd/decerver#107]
go go1.3.3 linux/amd64
git 1.9.3
mercurial 2.8.1-1
gmp 5.1.2
curl 7.32.0 
Fedora 20

I followed the tutorial located here:
https://decerver.io/tutorials/
and tried to start the decever, I recieved this call-stack:
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x70735a]

goroutine 16 [running]:
runtime.panic(0xac6ec0, 0x11f2b73)
	/usr/lib/golang/src/pkg/runtime/panic.c:279 +0xf5
github.com/eris-ltd/thelonious/Godeps/_workspace/src/github.com/eris-ltd/epm-go/utils.resolveDecerverRoot(0x0, 0x0)
	/etc/go/src/github.com/eris-ltd/thelonious/Godeps/_workspace/src/github.com/eris-ltd/epm-go/utils/utils.go:24 +0xfa
github.com/eris-ltd/thelonious/Godeps/_workspace/src/github.com/eris-ltd/epm-go/utils.init()
	/etc/go/src/github.com/eris-ltd/thelonious/Godeps/_workspace/src/github.com/eris-ltd/epm-go/utils/utils.go:34 +0x16f
github.com/eris-ltd/thelonious/Godeps/_workspace/src/github.com/eris-ltd/lllc-server.init()
	/etc/go/src/github.com/eris-ltd/thelonious/Godeps/_workspace/src/github.com/eris-ltd/lllc-server/server.go:215 +0xa7
github.com/eris-ltd/thelonious/Godeps/_workspace/src/github.com/eris-ltd/epm-go/epm.init()
	/etc/go/src/github.com/eris-ltd/thelonious/Godeps/_workspace/src/github.com/eris-ltd/epm-go/epm/test.go:148 +0x67
github.com/eris-ltd/thelonious/monk.init()
	/etc/go/src/github.com/eris-ltd/thelonious/monk/utils.go:631 +0x5d
github.com/eris-ltd/decerver-modules/monk.init()
	/etc/go/src/github.com/eris-ltd/decerver-modules/monk/monkmodule.go:319 +0x46
main.init()
	/etc/go/src/github.com/eris-ltd/decerver/cmd/decerver/main.go:39 +0x4b

goroutine 19 [finalizer wait]:
runtime.park(0x4272a0, 0x12116c8, 0x11f5e69)
	/usr/lib/golang/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x12116c8, 0x11f5e69)
	/usr/lib/golang/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
	/usr/lib/golang/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
	/usr/lib/golang/src/pkg/runtime/proc.c:1445

goroutine 17 [syscall]:
runtime.goexit()
	/usr/lib/golang/src/pkg/runtime/proc.c:1445

**Comment by ebuchman** [comment]
The issue seems to be the `user.Current()` function.

Note me asking myself how this function could ever err: https://github.com/eris-ltd/epm-go/blob/master/utils/utils.go#L33

Apparently, you managed to make it err :D

Note this: https://stackoverflow.com/questions/26575662/user-current-not-implemented-on-linux-amd64-with-fresh-golang-on-fedora

You may need to try compiling with gccgo. Apparently it's a known problem.

The following may serve as a minimal working example of the error. Please copy it into a `test.go` and try `go run test.go`. I suspect you will see the error. You may need to look into using gccgo rather than the default go compiler.

```
package main
import (
  "fmt"
  "os/user"
)
func main(){
  usr, err := user.Current()
  fmt.Println(usr, err)
}
```

**Comment by DennisHaper** [comment]
That worked. Thanks for your help, sorry for filing a bug due to user error!

**Comment by compleatang** [comment]
not a problem in the slightest, we welcome all the questions!  :+1:
