### ISSUE TITLE
issue rebuilding decerver to read own config settings

### ISSUE THREAD

**Issue by jdevoo** [eris-ltd/decerver#85]
I have tried to make simple changes to the source but cannot get a new decerver executable.
I posted the Go part on a [related SO question](http://stackoverflow.com/questions/26694271/go-install-doesnt-create-any-bin-file/27887283#27887283) which includes my go env.

In this instance, I replaced dc.ReadConfig("") with dc.ReadConfig("config.json") to pull from my changed settings.

**Comment by compleatang** [comment]
We definitely should support multiple config files without having to modify the source code. Ideally this should be a flag from the command line.

**Comment by androlo** [comment]
yes. All the file IO is tied to a settable root directory, meaning if that is changed then the entire system should change with it, without any problems. since we don't have a cli yet i hard code ~/.decerver in as root ('%USERPROFILE%\.decerver' in windows), but that we can change.

**Comment by androlo** [comment]
haha looks like it drops the '\' between % and . in the windows thing. Wonder why (it's there when you edit).

**Comment by jdevoo** [comment]
I managed to get my decerver rebuilt after issuing a `go get -x` from the cmd/decerver directory. Still puzzled why a basic `go install` from the main directory didn't work.

decerver now pulls from my config.json file but didn't create a "decerver.log" inside logs
    {
	"decerverDirectory": "/home/jdevoo/.decerver",
	"logFile": "decerver.log",
	"maxClients": 10,
	"portNumber": 3000
    }

**Comment by compleatang** [comment]
good question JP. 

so many go libraries are going to this format where the library itself is in the root directory and where the command line tool is in `rootdir/cmd/cli_name` folders. this makes it easy for go-docs.

as a comparison you can see the structure of legalmarkdown which is the reverse (based on the way ruby libs typically work) and has the command line tool in the root directory of the library and the library files in another directory. The godocs for `lmd` are a bit of a mess because of this folder structure, and generally we find the `lib/cmd/cli` format helpful. It is a bit awkward tho for folks coming from other languages. I'll be moving that around for the next release of legalmarkdown to reflect the emerging consensus on how to structure go libraries.

**Comment by androlo** [comment]
this is about adding flags to decerver, which we will do. creating new issue for that, closing.
